# Generated by Django 2.2.4 on 2019-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('img_url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
